[package]
name = "proposal_validator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path="src/lib.rs"


[dependencies]
candid = "0.10"
ic-cdk = "0.16"
serde = "1.0"
icrc-ledger-types = "0.1.6"

ic-toolkit-utils = {path = "../ic-toolkit-utils"}
